// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.1
// source: proto/fibonacci.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensagem de Request
type RequestFibo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P1 int32 `protobuf:"varint,2,opt,name=P1,proto3" json:"P1,omitempty"`
}

func (x *RequestFibo) Reset() {
	*x = RequestFibo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fibonacci_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestFibo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFibo) ProtoMessage() {}

func (x *RequestFibo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fibonacci_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFibo.ProtoReflect.Descriptor instead.
func (*RequestFibo) Descriptor() ([]byte, []int) {
	return file_proto_fibonacci_proto_rawDescGZIP(), []int{0}
}

func (x *RequestFibo) GetP1() int32 {
	if x != nil {
		return x.P1
	}
	return 0
}

//Mensagem de resposta
type ReplyFibo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N int32 `protobuf:"varint,1,opt,name=N,proto3" json:"N,omitempty"`
}

func (x *ReplyFibo) Reset() {
	*x = ReplyFibo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fibonacci_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyFibo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyFibo) ProtoMessage() {}

func (x *ReplyFibo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fibonacci_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyFibo.ProtoReflect.Descriptor instead.
func (*ReplyFibo) Descriptor() ([]byte, []int) {
	return file_proto_fibonacci_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyFibo) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

var File_proto_fibonacci_proto protoreflect.FileDescriptor

var file_proto_fibonacci_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x66, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63,
	0x63, 0x69, 0x22, 0x1d, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x69, 0x62,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x50, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x50,
	0x31, 0x22, 0x19, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x46, 0x69, 0x62, 0x6f, 0x12, 0x0c,
	0x0a, 0x01, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x4e, 0x32, 0x43, 0x0a, 0x09,
	0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x12, 0x36, 0x0a, 0x04, 0x46, 0x69, 0x62,
	0x6f, 0x12, 0x16, 0x2e, 0x66, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x69, 0x62, 0x6f, 0x1a, 0x14, 0x2e, 0x66, 0x69, 0x62, 0x6f,
	0x6e, 0x61, 0x63, 0x63, 0x69, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x46, 0x69, 0x62, 0x6f, 0x22,
	0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x2f, 0x67, 0x65, 0x6e,
	0x3b, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_fibonacci_proto_rawDescOnce sync.Once
	file_proto_fibonacci_proto_rawDescData = file_proto_fibonacci_proto_rawDesc
)

func file_proto_fibonacci_proto_rawDescGZIP() []byte {
	file_proto_fibonacci_proto_rawDescOnce.Do(func() {
		file_proto_fibonacci_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_fibonacci_proto_rawDescData)
	})
	return file_proto_fibonacci_proto_rawDescData
}

var file_proto_fibonacci_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_fibonacci_proto_goTypes = []interface{}{
	(*RequestFibo)(nil), // 0: fibonacci.RequestFibo
	(*ReplyFibo)(nil),   // 1: fibonacci.ReplyFibo
}
var file_proto_fibonacci_proto_depIdxs = []int32{
	0, // 0: fibonacci.Fibonacci.Fibo:input_type -> fibonacci.RequestFibo
	1, // 1: fibonacci.Fibonacci.Fibo:output_type -> fibonacci.ReplyFibo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fibonacci_proto_init() }
func file_proto_fibonacci_proto_init() {
	if File_proto_fibonacci_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_fibonacci_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestFibo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fibonacci_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyFibo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_fibonacci_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fibonacci_proto_goTypes,
		DependencyIndexes: file_proto_fibonacci_proto_depIdxs,
		MessageInfos:      file_proto_fibonacci_proto_msgTypes,
	}.Build()
	File_proto_fibonacci_proto = out.File
	file_proto_fibonacci_proto_rawDesc = nil
	file_proto_fibonacci_proto_goTypes = nil
	file_proto_fibonacci_proto_depIdxs = nil
}
